version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}
  local_media: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: sistemita_local_django
    container_name: sistemita_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
      - local_media:/app/temario/media
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: sistemita_production_postgres
    container_name: sistemita_local_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres
