version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_media: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: sistemita_production_django
    container_name: sistemita_production_django
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start
    ports:
      - "8000:8000"
    volumes:
      - production_media:/app/sistemita/media
    restart: unless-stopped

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: sistemita_production_postgres
    container_name: sistemita_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data:Z
      - production_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.production/.postgres
    restart: unless-stopped

  redis:
    image: redis:5.0
    container_name: sistemita_production_redis
    restart: unless-stopped

  nginx:
    image: nginx:1.19-alpine
    container_name: sistemita_production_nginx
    restart: always
    ports:
      - 8080:80
    volumes:
      - production_media:/media
      - ./compose/production/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - django
    restart: unless-stopped
