version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_media: {}
  production_traefik: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: sistemita_production_django
    container_name: sistemita_production_django
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start
    volumes:
      - production_media:/app/sistemita/media
    restart: unless-stopped

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: sistemita_production_postgres
    container_name: sistemita_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data:Z
      - production_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.production/.postgres
    restart: unless-stopped

  redis:
    image: redis:5.0
    container_name: sistemita_production_redis
    restart: unless-stopped

  celeryworker:
    <<: *django
    image: sistemita_production_celeryworker
    container_name: sistemita_production_celeryworker
    command: /start-celeryworker
    restart: unless-stopped

  celerybeat:
    <<: *django
    image: sistemita_production_celerybeat
    container_name: sistemita_production_celerybeat
    command: /start-celerybeat
    restart: unless-stopped

  flower:
    <<: *django
    image: sistemita_production_flower
    container_name: sistemita_production_flower
    command: /start-flower
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: sistemita_production_nginx
    container_name: sistemita_production_nginx
    ports:
      - 8080:80
    volumes:
      - production_media:/www/media
    depends_on:
      - django
    restart: unless-stopped

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: sistemita_production_traefik
    container_name: sistemita_production_traefik
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme:z
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    restart: unless-stopped
