# Generated by Django 3.0.6 on 2020-06-17 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Distrito',
                'verbose_name_plural': 'Distritos',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('codigo', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('distrito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Distrito', verbose_name='Distrito')),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
                'ordering': ('nombre',),
            },
        ),
        migrations.AddField(
            model_name='distrito',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Provincia', verbose_name='Provincia'),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('razon_social', models.CharField(max_length=128, verbose_name='Razón Social')),
                ('cuit', models.CharField(max_length=11, verbose_name='CUIT')),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=14, verbose_name='Teléfono')),
                ('calle', models.CharField(blank=True, max_length=35, verbose_name='Calle')),
                ('numero', models.CharField(blank=True, max_length=12, verbose_name='Número')),
                ('piso', models.CharField(blank=True, max_length=4, verbose_name='Piso')),
                ('dpto', models.CharField(blank=True, max_length=4, verbose_name='Departamento')),
                ('tipo_envio_factura', models.CharField(choices=[('C', 'Correo'), ('U', 'Link')], default='C', max_length=1, verbose_name='Forma de envío')),
                ('link_envio_factura', models.URLField(blank=True, verbose_name='URL de envío')),
                ('correo_envio_factura', models.EmailField(blank=True, max_length=254, verbose_name='Correo de envío')),
                ('distrito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Distrito', verbose_name='Distrito')),
                ('localidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Localidad', verbose_name='Localidad')),
                ('provincia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Provincia', verbose_name='Provincia')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ('razon_social',),
            },
        ),
    ]
