# Generated by Django 3.0.6 on 2020-06-17 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200602_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Departamento', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('codigo', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
            },
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ('razon_social',), 'verbose_name': 'cliente', 'verbose_name_plural': 'clientes'},
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nombre',
        ),
        migrations.AddField(
            model_name='cliente',
            name='calle',
            field=models.CharField(blank=True, max_length=35, verbose_name='Calle'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(default='sin@correo.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='cuit',
            field=models.CharField(default='20000000007', max_length=11, verbose_name='CUIT'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='dpto',
            field=models.CharField(blank=True, max_length=4, verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero',
            field=models.CharField(blank=True, max_length=12, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='piso',
            field=models.CharField(blank=True, max_length=4, verbose_name='Piso'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='razon_social',
            field=models.CharField(default='Sin razón social', max_length=128, verbose_name='Razón Social'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_envio_factura',
            field=models.CharField(choices=[('C', 'Correo'), ('U', 'Link')], default='C', max_length=1, verbose_name='Forma de envio de factura'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('razon_social', models.CharField(max_length=128, verbose_name='Razón Social')),
                ('cuit', models.CharField(max_length=11, verbose_name='CUIT')),
                ('correo', models.EmailField(max_length=254)),
                ('calle', models.CharField(blank=True, max_length=35, verbose_name='Calle')),
                ('numero', models.CharField(blank=True, max_length=12, verbose_name='Número')),
                ('piso', models.CharField(blank=True, max_length=4, verbose_name='Piso')),
                ('dpto', models.CharField(blank=True, max_length=4, verbose_name='Departamento')),
                ('cbu', models.CharField(blank=True, max_length=22, null=True, verbose_name='CBU')),
                ('localidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Localidad', verbose_name='Localidad')),
            ],
            options={
                'verbose_name': 'proveedor',
                'verbose_name_plural': 'proveedores',
                'ordering': ('razon_social',),
            },
        ),
        migrations.AddField(
            model_name='departamento',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Provincia', verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Localidad', verbose_name='Localidad'),
        ),
    ]
