# Generated by Django 3.0.7 on 2020-07-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(default=0, max_length=14, verbose_name='Teléfono'),
            preserve_default=False,
        ),
    ]
