# Generated by Django 3.0.7 on 2020-09-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200729_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='cobrado',
            field=models.BooleanField(default=False),
        ),
    ]
