# Generated by Django 3.0.7 on 2020-10-23 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201015_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaProveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('fecha', models.DateField()),
                ('moneda', models.CharField(choices=[('P', '$'), ('D', 'U$$')], default='P', max_length=1)),
                ('monto', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cobrado', models.BooleanField(default=False)),
                ('archivos', models.ManyToManyField(blank=True, to='core.Archivo')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Proveedor')),
            ],
            options={
                'verbose_name': 'factura proveedor',
                'verbose_name_plural': 'facturas proveedores',
                'ordering': ('fecha',),
            },
        ),
    ]
