# Generated by Django 3.0.7 on 2020-11-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_facturaproveedor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='monto',
            new_name='neto',
        ),
        migrations.RenameField(
            model_name='facturaproveedor',
            old_name='monto',
            new_name='neto',
        ),
        migrations.AddField(
            model_name='factura',
            name='detalle',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='iva',
            field=models.PositiveSmallIntegerField(default=21),
        ),
        migrations.AddField(
            model_name='factura',
            name='numero',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='factura',
            name='tipo',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='factura',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='facturaproveedor',
            name='detalle',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='facturaproveedor',
            name='iva',
            field=models.PositiveSmallIntegerField(default=21),
        ),
        migrations.AddField(
            model_name='facturaproveedor',
            name='numero',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='facturaproveedor',
            name='tipo',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='facturaproveedor',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
