# Generated by Django 3.0.7 on 2020-11-13 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201113_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaproveedor',
            name='factura',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Factura'),
            preserve_default=False,
        ),
    ]
