# Generated by Django 3.0.7 on 2020-11-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_facturaproveedor_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='tipo',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('NCA', 'NC A'), ('NCB', 'NC B'), ('FCPYME', 'FC PYME'), ('NCFCPYME', 'NC FCPYME')], default='A', max_length=8),
        ),
        migrations.AlterField(
            model_name='facturaproveedor',
            name='tipo',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('NCA', 'NC A'), ('NCB', 'NC B'), ('FCPYME', 'FC PYME'), ('NCFCPYME', 'NC FCPYME')], default='A', max_length=8),
        ),
    ]
