# Generated by Django 3.0.7 on 2021-01-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20201119_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cuit',
            field=models.CharField(max_length=11, unique=True, verbose_name='CUIT'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='moneda',
            field=models.CharField(choices=[('P', '$'), ('D', 'U$D')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='facturaproveedor',
            name='moneda',
            field=models.CharField(choices=[('P', '$'), ('D', 'U$D')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='mediopago',
            name='nombre',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='moneda',
            field=models.CharField(choices=[('P', '$'), ('D', 'U$D')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='cuit',
            field=models.CharField(max_length=11, unique=True, verbose_name='CUIT'),
        ),
    ]
