# Generated by Django 3.0.7 on 2021-03-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210118_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='tipo',
            field=models.CharField(choices=[('A', 'A'), ('ARETEN', 'A SUJETA A RETENCIÓN'), ('B', 'B'), ('C', 'C'), ('M', 'M'), ('NCA', 'NC A'), ('NCB', 'NC B'), ('FCPYME', 'FC PYME'), ('NCFCPYME', 'NC FCPYME')], default='A', max_length=8),
        ),
        migrations.AlterField(
            model_name='facturaproveedor',
            name='tipo',
            field=models.CharField(choices=[('A', 'A'), ('ARETEN', 'A SUJETA A RETENCIÓN'), ('B', 'B'), ('C', 'C'), ('M', 'M'), ('NCA', 'NC A'), ('NCB', 'NC B'), ('FCPYME', 'FC PYME'), ('NCFCPYME', 'NC FCPYME')], default='A', max_length=8),
        ),
    ]
