# Generated by Django 3.1.7 on 2021-06-20 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobranza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='modificado')),
                ('fecha', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
            options={
                'verbose_name': 'cobranza',
                'verbose_name_plural': 'cobranzas',
                'db_table': 'accounting_cliente_cobranza',
                'ordering': ('creado',),
            },
        ),
        migrations.CreateModel(
            name='CobranzaFactura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='modificado')),
                ('ganancias', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('ingresos_brutos', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cobranza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobranza_facturas', to='accounting.cobranza')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.factura')),
            ],
            options={
                'verbose_name': 'factura cobranza',
                'verbose_name_plural': 'facturas cobranza',
                'db_table': 'accounting_cliente_cobranza_factura',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='modificado')),
                ('fecha', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('pagado', models.BooleanField(default=False)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proveedor')),
            ],
            options={
                'verbose_name': 'pago',
                'verbose_name_plural': 'pagos',
                'db_table': 'accounting_proveedor_pago',
                'ordering': ('creado',),
            },
        ),
        migrations.CreateModel(
            name='PagoFactura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='modificado')),
                ('ganancias', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('ingresos_brutos', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.facturaproveedor')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pago_facturas', to='accounting.pago')),
            ],
            options={
                'verbose_name': 'factura pago',
                'verbose_name_plural': 'facturas pago',
                'db_table': 'accounting_proveedor_pago_factura',
            },
        ),
        migrations.CreateModel(
            name='PagoFacturaPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('metodo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mediopago')),
                ('pago_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pago_factura_pagos', to='accounting.pagofactura')),
            ],
            options={
                'verbose_name': 'pago factura pago',
                'verbose_name_plural': 'pagos factura pago',
                'db_table': 'accounting_proveedor_pago_factura_pago',
            },
        ),
        migrations.CreateModel(
            name='CobranzaFacturaPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cobranza_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobranza_factura_pagos', to='accounting.cobranzafactura')),
                ('metodo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mediopago')),
            ],
            options={
                'verbose_name': 'pago factura cobranza',
                'verbose_name_plural': 'pagos factura cobranza',
                'db_table': 'accounting_cliente_cobranza_factura_pago',
            },
        ),
    ]
