# Generated by Django 3.1.7 on 2021-06-13 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210613_1439'),
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobranzafacturapago',
            name='metodo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mediopago'),
        ),
        migrations.AlterField(
            model_name='pagofacturapago',
            name='metodo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mediopago'),
        ),
    ]
