# Generated by Django 3.1.7 on 2021-06-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20210613_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobranza',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creado'),
        ),
        migrations.AlterField(
            model_name='cobranza',
            name='modificado',
            field=models.DateTimeField(auto_now=True, verbose_name='modificado'),
        ),
        migrations.AlterField(
            model_name='cobranzafactura',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creado'),
        ),
        migrations.AlterField(
            model_name='cobranzafactura',
            name='modificado',
            field=models.DateTimeField(auto_now=True, verbose_name='modificado'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creado'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='modificado',
            field=models.DateTimeField(auto_now=True, verbose_name='modificado'),
        ),
        migrations.AlterField(
            model_name='pagofactura',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creado'),
        ),
        migrations.AlterField(
            model_name='pagofactura',
            name='modificado',
            field=models.DateTimeField(auto_now=True, verbose_name='modificado'),
        ),
    ]
