# Generated by Django 3.1.7 on 2021-11-04 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_field_pagado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobranza',
            name='moneda',
            field=models.CharField(choices=[('P', '$'), ('D', 'USD')], default='P', max_length=1),
        ),
    ]
