# Generated by Django 2.2.2 on 2019-07-19 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_clientes', '0002_auto_20190719_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscripcionencursopublico',
            old_name='cant_inscriptos',
            new_name='cantidad_de_inscriptos',
        ),
    ]
