# Generated by Django 2.2.2 on 2019-06-16 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_clientes', '0002_auto_20190602_0237'),
    ]

    operations = [
        migrations.CreateModel(
            name='PorcentajesAportadosAFondosYDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_fondo_administrativo', models.DecimalField(decimal_places=2, max_digits=2)),
                ('porcentaje_fondo_liquido', models.DecimalField(decimal_places=2, max_digits=2)),
                ('porcentaje_delivery', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
