# Generated by Django 2.2.2 on 2019-07-25 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_clientes', '0004_auto_20190719_1713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultor',
            options={'verbose_name_plural': 'Consultores'},
        ),
    ]
