# Generated by Django 2.2.2 on 2019-06-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_clientes', '0005_deliverypendientedecobro_fondoadministrativopendientedecobro_fondoliquidopendientedecobro'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacliente',
            name='porcentaje_para_mentoring_sobre_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=2),
        ),
    ]
