# Generated by Django 2.2.4 on 2019-08-18 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_clientes', '0007_consultor_cbu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultor',
            name='cbu',
            field=models.DecimalField(decimal_places=0, max_digits=22, null=True),
        ),
    ]
