# Generated by Django 2.2.4 on 2019-08-28 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_clientes', '0011_movimientobancario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimientobancario',
            old_name='sucursal_origen',
            new_name='codigo_sucursal',
        ),
    ]
