# Generated by Django 2.2.2 on 2019-06-24 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_clientes', '0011_mentoringpendientedecobro_mentor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeliveryPendienteDeCobro',
            new_name='DeliveryYMentoringPendientesDeCobro',
        ),
    ]
