# Generated by Django 2.2.4 on 2019-08-31 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_clientes', '0012_auto_20190827_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoclientetransferenciaaliqueed',
            name='movimiento_bancario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='facturacion_clientes.MovimientoBancario'),
            preserve_default=False,
        ),
    ]
