# Generated by Django 2.2.2 on 2019-06-24 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_clientes', '0012_auto_20190624_0319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fondoliquidopendientedecobro',
            name='factura',
        ),
        migrations.RemoveField(
            model_name='fondoliquidopendientedecobro',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='fondoliquidopendientedecobro',
            name='monto',
        ),
        migrations.RemoveField(
            model_name='fondoliquidopendientedecobro',
            name='monto_currency',
        ),
    ]
