# Generated by Django 2.2.2 on 2019-06-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_clientes', '0014_auto_20190624_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='dias_demora_pago',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
