# Generated by Django 2.2.4 on 2019-09-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_clientes', '0014_auto_20190831_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarjetaDeCreditoCorporativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
            ],
        ),
    ]
