# Generated by Django 2.2.2 on 2019-06-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_clientes', '0015_cliente_dias_demora_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='dias_demora_pago',
            field=models.IntegerField(default=0),
        ),
    ]
