# Generated by Django 2.2.2 on 2019-06-24 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_clientes', '0017_auto_20190624_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaDeConsultorACliente',
            fields=[
                ('facturacliente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='facturacion_clientes.FacturaCliente')),
                ('consultor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion_clientes.Consultor')),
            ],
            bases=('facturacion_clientes.facturacliente',),
        ),
    ]
