# Generated by Django 2.2.2 on 2019-06-24 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_clientes', '0018_facturadeconsultoracliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaDeLiqueedACliente',
            fields=[
                ('facturacliente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='facturacion_clientes.FacturaCliente')),
            ],
            bases=('facturacion_clientes.facturacliente',),
        ),
    ]
