# Generated by Django 2.2.4 on 2019-09-07 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_clientes', '0018_pagoclientetransferenciaaconsultor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagoclientetransferenciaaliqueed',
            name='movimiento_bancario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='facturacion_clientes.MovimientoBancario'),
            preserve_default=False,
        ),
    ]
