# Generated by Django 2.2.4 on 2019-09-07 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_clientes', '0019_auto_20190907_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoliqueedaconsultor',
            name='movimiento_bancario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='facturacion_clientes.MovimientoBancario'),
            preserve_default=False,
        ),
    ]
