# Generated by Django 2.2.4 on 2019-11-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_clientes', '0021_pagoimpuestoalcheque_movimiento_bancario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cuit',
            field=models.BigIntegerField(null=True),
        ),
    ]
