# Generated by Django 2.2.2 on 2019-06-28 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_clientes', '0022_auto_20190627_0054'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FondoLiquidoPendienteDeCobro',
            new_name='FondoLiquido',
        ),
    ]
