# Generated by Django 2.2.2 on 2019-06-28 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_clientes', '0023_auto_20190628_0137'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeliveryYMentoringPendientesDeCobro',
            new_name='DeliveryYMentoring',
        ),
    ]
