# Generated by Django 2.2.7 on 2019-11-09 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_clientes', '0023_cliente_descripcion_en_resumen_bancario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultor',
            name='cbu',
        ),
        migrations.CreateModel(
            name='FacturadorDeConsultor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuit', models.BigIntegerField(null=True)),
                ('cbu', models.DecimalField(decimal_places=0, max_digits=22, null=True)),
                ('consultor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion_clientes.Consultor')),
            ],
        ),
    ]
