# Generated by Django 2.2.2 on 2019-06-28 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_clientes', '0024_auto_20190628_0158'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MentoringPendienteDeCobro',
            new_name='Mentoring',
        ),
    ]
