# Generated by Django 2.2.7 on 2020-02-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_clientes', '0028_auto_20200224_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientocuenta',
            name='cobrado',
            field=models.BooleanField(default=False),
        ),
    ]
