# Generated by Django 2.2.10 on 2020-03-13 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_clientes', '0032_auto_20200311_1348'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PagoLiqueedAConsultorSinConciliar',
            new_name='PagoPlanificadoLiqueedAConsultor',
        ),
    ]
