# Generated by Django 2.2.10 on 2020-03-13 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_clientes', '0034_remove_pagoplanificadoliqueedaconsultor_movimiento_bancario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoplanificadoliqueedaconsultor',
            name='delivery_individual',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='facturacion_clientes.DeliveryIndividual'),
            preserve_default=False,
        ),
    ]
