# Generated by Django 2.2.10 on 2020-03-13 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_clientes', '0035_pagoplanificadoliqueedaconsultor_delivery_individual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagoliqueedaconsultor',
            name='factura',
        ),
        migrations.AddField(
            model_name='pagoliqueedaconsultor',
            name='delivery_individual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facturacion_clientes.DeliveryIndividual'),
        ),
    ]
