# Generated by Django 3.1.7 on 2021-06-20 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.FileField(upload_to='archivos/documentos/')),
            ],
            options={
                'verbose_name': 'archivo',
                'verbose_name_plural': 'archivos',
                'db_table': 'core_archivos',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='modificado')),
                ('razon_social', models.CharField(max_length=128, verbose_name='Razón Social')),
                ('cuit', models.CharField(max_length=11, unique=True, verbose_name='CUIT')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=14, verbose_name='Teléfono')),
                ('calle', models.CharField(blank=True, max_length=35, verbose_name='Calle')),
                ('numero', models.CharField(blank=True, max_length=12, verbose_name='Número')),
                ('piso', models.CharField(blank=True, max_length=4, verbose_name='Piso')),
                ('dpto', models.CharField(blank=True, max_length=4, verbose_name='Departamento')),
                ('tipo_envio_factura', models.CharField(blank=True, choices=[('C', 'Correo'), ('U', 'Link')], default='C', max_length=1, verbose_name='Forma de envío')),
                ('link_envio_factura', models.URLField(blank=True, verbose_name='URL de envío')),
                ('correo_envio_factura', models.EmailField(blank=True, max_length=254, verbose_name='Correo de envío')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ('razon_social',),
            },
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Distrito',
                'verbose_name_plural': 'Distritos',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='modificado')),
                ('numero', models.CharField(max_length=20, verbose_name='número')),
                ('fecha', models.DateField()),
                ('detalle', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('A', 'A'), ('ARETEN', 'A SUJETA A RETENCIÓN'), ('B', 'B'), ('C', 'C'), ('RC', 'Recibo C'), ('E', 'E'), ('FCPYME', 'FC PYME'), ('M', 'M'), ('NCA', 'NC A'), ('NCARETEN', 'NC A SUJETA A RETENCION'), ('NCB', 'NC B'), ('NCC', 'NC C'), ('NCFCPYME', 'NC FCPYME'), ('NCM', 'NC M')], default='A', max_length=8)),
                ('moneda', models.CharField(choices=[('P', '$'), ('D', 'USD')], default='P', max_length=1)),
                ('neto', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12)),
                ('iva', models.PositiveSmallIntegerField(default=21)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cobrado', models.BooleanField(default=False)),
                ('archivos', models.ManyToManyField(blank=True, to='core.Archivo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
            options={
                'verbose_name': 'factura',
                'verbose_name_plural': 'facturas',
                'ordering': ('fecha',),
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('distrito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.distrito', verbose_name='Distrito')),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='MedioPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='modificado')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'medio de pago',
                'verbose_name_plural': 'medios de pago',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('codigo', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Código')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='modificado')),
                ('razon_social', models.CharField(max_length=128, verbose_name='Razón Social')),
                ('cuit', models.CharField(max_length=11, unique=True, verbose_name='CUIT')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=14, verbose_name='Teléfono')),
                ('calle', models.CharField(blank=True, max_length=35, verbose_name='Calle')),
                ('numero', models.CharField(blank=True, max_length=12, verbose_name='Número')),
                ('piso', models.CharField(blank=True, max_length=4, verbose_name='Piso')),
                ('dpto', models.CharField(blank=True, max_length=4, verbose_name='Departamento')),
                ('cbu', models.CharField(blank=True, max_length=22, verbose_name='CBU')),
                ('distrito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.distrito', verbose_name='Distrito')),
                ('localidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.localidad', verbose_name='Localidad')),
                ('provincia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.provincia', verbose_name='Provincia')),
            ],
            options={
                'verbose_name': 'proveedor',
                'verbose_name_plural': 'proveedores',
                'ordering': ('razon_social',),
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='modificado')),
                ('fecha', models.DateField()),
                ('moneda', models.CharField(choices=[('P', '$'), ('D', 'USD')], default='P', max_length=1)),
                ('monto', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
            options={
                'verbose_name': 'orden de compra',
                'verbose_name_plural': 'ordenes de compras',
                'ordering': ('fecha',),
            },
        ),
        migrations.CreateModel(
            name='FacturaProveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='modificado')),
                ('numero', models.CharField(max_length=20, verbose_name='número')),
                ('fecha', models.DateField()),
                ('detalle', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('A', 'A'), ('ARETEN', 'A SUJETA A RETENCIÓN'), ('B', 'B'), ('C', 'C'), ('RC', 'Recibo C'), ('E', 'E'), ('FCPYME', 'FC PYME'), ('M', 'M'), ('NCA', 'NC A'), ('NCARETEN', 'NC A SUJETA A RETENCION'), ('NCB', 'NC B'), ('NCC', 'NC C'), ('NCFCPYME', 'NC FCPYME'), ('NCM', 'NC M')], default='A', max_length=8)),
                ('moneda', models.CharField(choices=[('P', '$'), ('D', 'USD')], default='P', max_length=1)),
                ('neto', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12)),
                ('iva', models.PositiveSmallIntegerField(default=21)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cobrado', models.BooleanField(default=False)),
                ('archivos', models.ManyToManyField(blank=True, to='core.Archivo')),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facturas_proveedor', to='core.factura')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proveedor')),
            ],
            options={
                'verbose_name': 'factura proveedor',
                'verbose_name_plural': 'facturas proveedores',
                'ordering': ('fecha',),
            },
        ),
        migrations.AddField(
            model_name='distrito',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.provincia', verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='distrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.distrito', verbose_name='Distrito'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.localidad', verbose_name='Localidad'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.provincia', verbose_name='Provincia'),
        ),
    ]
