# Generated by Django 3.1.7 on 2021-09-29 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='porcentaje_fondo',
            field=models.PositiveSmallIntegerField(default=15),
        ),
    ]
