# Generated by Django 3.1.7 on 2021-04-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='tipo',
            field=models.CharField(choices=[('A', 'A'), ('ARETEN', 'A SUJETA A RETENCIÓN'), ('B', 'B'), ('C', 'C'), ('FCPYME', 'FC PYME'), ('M', 'M'), ('NCA', 'NC A'), ('NCARETEN', 'NC A SUJETA A RETENCION'), ('NCB', 'NC B'), ('NCC', 'NC C'), ('NCFCPYME', 'NC FCPYME'), ('NCM', 'NC M')], default='A', max_length=8),
        ),
        migrations.AlterField(
            model_name='facturaproveedor',
            name='tipo',
            field=models.CharField(choices=[('A', 'A'), ('ARETEN', 'A SUJETA A RETENCIÓN'), ('B', 'B'), ('C', 'C'), ('FCPYME', 'FC PYME'), ('M', 'M'), ('NCA', 'NC A'), ('NCARETEN', 'NC A SUJETA A RETENCION'), ('NCB', 'NC B'), ('NCC', 'NC C'), ('NCFCPYME', 'NC FCPYME'), ('NCM', 'NC M')], default='A', max_length=8),
        ),
    ]
