# Generated by Django 3.1.7 on 2021-11-26 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_factura_porcentaje_fondo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaImputada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='modificado')),
                ('fecha', models.DateField()),
                ('moneda', models.CharField(choices=[('P', '$'), ('D', 'USD')], default='P', max_length=1)),
                ('monto_facturas', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('monto_nota_de_credito', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_factura', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('facturas', models.ManyToManyField(related_name='facturas_imputacion', to='core.Factura')),
                ('nota_de_credito', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factura_nc', to='core.factura')),
            ],
            options={
                'verbose_name': 'factura imputada',
                'verbose_name_plural': 'facturas imputadas',
                'ordering': ('fecha',),
            },
        ),
    ]
