# Generated by Django 3.1.7 on 2021-12-02 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_facturaimputada'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='monto_imputado',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='facturaproveedor',
            name='monto_imputado',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
