# Generated by Django 3.1.7 on 2021-06-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210612_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=14, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_envio_factura',
            field=models.CharField(blank=True, choices=[('C', 'Correo'), ('U', 'Link')], default='C', max_length=1, verbose_name='Forma de envío'),
        ),
    ]
