# Generated by Django 3.1.7 on 2021-06-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210612_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='cbu',
            field=models.CharField(blank=True, default='', max_length=22, verbose_name='CBU'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='correo',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(blank=True, max_length=14, verbose_name='Teléfono'),
        ),
    ]
