# Generated by Django 3.1.7 on 2021-06-13 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210613_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaproveedor',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facturas_proveedor', to='core.factura'),
        ),
    ]
