# Generated by Django 3.1.7 on 2022-03-01 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_facturaproveedor_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facturaimputada',
            options={'ordering': ('-fecha',), 'verbose_name': 'factura imputada', 'verbose_name_plural': 'facturas imputadas'},
        ),
        migrations.AlterModelOptions(
            name='facturaproveedorimputada',
            options={'ordering': ('-fecha',), 'verbose_name': 'factura proveedor imputada', 'verbose_name_plural': 'facturas proveedor imputadas'},
        ),
    ]
