# Generated by Django 3.1.7 on 2021-06-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210613_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='moneda',
            field=models.CharField(choices=[('P', '$'), ('D', 'USD')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='facturaproveedor',
            name='moneda',
            field=models.CharField(choices=[('P', '$'), ('D', 'USD')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='moneda',
            field=models.CharField(choices=[('P', '$'), ('D', 'USD')], default='P', max_length=1),
        ),
    ]
