# Generated by Django 3.1.7 on 2021-06-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210613_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='neto',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='facturaproveedor',
            name='neto',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
