# Generated by Django 3.1.7 on 2022-12-04 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_change_meta_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaDistribuida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='modificado')),
                ('distribuida', models.BooleanField(default=False)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.factura')),
            ],
            options={
                'verbose_name': 'factura distribuida',
                'verbose_name_plural': 'facturas distribuidas',
            },
        ),
    ]
