# Generated by Django 3.1.7 on 2021-06-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210613_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creado'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='modificado',
            field=models.DateTimeField(auto_now=True, verbose_name='modificado'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creado'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='modificado',
            field=models.DateTimeField(auto_now=True, verbose_name='modificado'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='numero',
            field=models.CharField(max_length=20, verbose_name='número'),
        ),
        migrations.AlterField(
            model_name='facturaproveedor',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creado'),
        ),
        migrations.AlterField(
            model_name='facturaproveedor',
            name='modificado',
            field=models.DateTimeField(auto_now=True, verbose_name='modificado'),
        ),
        migrations.AlterField(
            model_name='facturaproveedor',
            name='numero',
            field=models.CharField(max_length=20, verbose_name='número'),
        ),
        migrations.AlterField(
            model_name='mediopago',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creado'),
        ),
        migrations.AlterField(
            model_name='mediopago',
            name='modificado',
            field=models.DateTimeField(auto_now=True, verbose_name='modificado'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creado'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='modificado',
            field=models.DateTimeField(auto_now=True, verbose_name='modificado'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creado'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='modificado',
            field=models.DateTimeField(auto_now=True, verbose_name='modificado'),
        ),
    ]
