# Generated by Django 3.1.7 on 2022-12-13 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_facturadistribuida'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaDistribuidaProveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='modificado')),
                ('monto', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('factura_distribucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factura_distribuida_proveedores', to='core.facturadistribuida')),
                ('factura_proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facturas_distribuidas', to='core.facturaproveedor')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proveedor')),
            ],
            options={
                'verbose_name': 'factura distribuida a proveedor',
                'verbose_name_plural': 'facturas distribuidas a proveedores',
            },
        ),
    ]
