# Generated by Django 3.1.7 on 2023-01-19 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_facturadistribuidaproveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturadistribuidaproveedor',
            name='detalle',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
