# Generated by Django 3.1.7 on 2023-01-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_facturadistribuidaproveedor_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='proveedores',
            field=models.ManyToManyField(blank=True, to='core.Proveedor'),
        ),
    ]
