# Generated by Django 3.2 on 2023-01-23 17:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_factura_proveedores'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='porcentaje_socio_alan',
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=5, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='factura',
            name='porcentaje_socio_ariel',
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=5, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
