# Generated by Django 3.2 on 2023-02-22 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_model_ordencompra_to_contrato'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contrato',
            options={'ordering': ('fecha_desde',), 'verbose_name': 'contrato', 'verbose_name_plural': 'contratos'},
        ),
        migrations.RenameField(
            model_name='contrato',
            old_name='fecha',
            new_name='fecha_desde',
        ),
    ]
