# Generated by Django 3.2 on 2023-02-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_contrato_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='proveedores',
            field=models.ManyToManyField(blank=True, to='core.Proveedor'),
        ),
    ]
