# Generated by Django 3.2 on 2023-02-23 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_contrato_proveedores'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categoria_contrato', to='core.facturacategoria'),
        ),
    ]
