# Generated by Django 3.2 on 2023-02-23 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_contrato_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.contrato'),
        ),
    ]
