# Generated by Django 3.2 on 2023-03-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_factura_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='fecha_estimada_pago',
            field=models.DateField(blank=True, null=True),
        ),
    ]
