# Generated by Django 3.2 on 2023-03-28 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_factura_fecha_estimada_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaImpuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.TextField(blank=True, max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impuestos', to='core.factura')),
            ],
            options={
                'verbose_name': 'impuesto',
                'verbose_name_plural': 'impuestos',
            },
        ),
    ]
