# Generated by Django 3.2 on 2023-04-03 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_facturaimpuesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='core.contrato'),
        ),
    ]
