# Generated by Django 2.2.2 on 2019-07-19 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_clientes', '0001_squashed_0041_inscripcionencursopublico_cant_inscriptos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryindividual',
            name='movimientocuenta_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='facturacion_clientes.MovimientoCuenta'),
        ),
        migrations.AlterField(
            model_name='deliveryymentoring',
            name='movimientocuenta_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='facturacion_clientes.MovimientoCuenta'),
        ),
        migrations.AlterField(
            model_name='deudacliente',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion_clientes.FacturaCliente'),
        ),
        migrations.AlterField(
            model_name='deudacliente',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fondoadministrativo',
            name='movimientocuenta_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='facturacion_clientes.MovimientoCuenta'),
        ),
        migrations.AlterField(
            model_name='fondoliquido',
            name='movimientocuenta_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='facturacion_clientes.MovimientoCuenta'),
        ),
        migrations.AlterField(
            model_name='inscripcionencursopublico',
            name='cant_inscriptos',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inscripcionencursopublico',
            name='fecha_inscripcion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='mentoring',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion_clientes.Consultor'),
        ),
        migrations.AlterField(
            model_name='mentoring',
            name='movimientocuenta_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='facturacion_clientes.MovimientoCuenta'),
        ),
    ]
