# Generated by Django 2.2.4 on 2019-08-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_clientes', '0006_pagoimpuestoalcheque'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultor',
            name='cbu',
            field=models.DecimalField(decimal_places=0, default=None, max_digits=22),
            preserve_default=False,
        ),
    ]
