# Generated by Django 2.2.10 on 2020-03-13 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_clientes', '0033_auto_20200313_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagoplanificadoliqueedaconsultor',
            name='movimiento_bancario',
        ),
    ]
