#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python /app/manage.py collectstatic --noinput
python /app/manage.py migrate

/usr/local/bin/gunicorn --workers 3 config.wsgi --bind 0.0.0.0:5000 --chdir=/app
