log:
  level: INFO

entryPoints:
  web:
    # http
    address: ":80"
    http:
      # https://docs.traefik.io/routing/entrypoints/#entrypoint
      redirections:
        entryPoint:
          to: web-secure

  web-secure:
    # https
    address: ":443"

certificatesResolvers:
  letsencrypt:
    # https://docs.traefik.io/master/https/acme/#lets-encrypt
    acme:
      email: "daniel.padula@tutanota.com"
      storage: /etc/traefik/acme/acme.json
      # https://docs.traefik.io/master/https/acme/#httpchallenge
      httpChallenge:
        entryPoint: web

http:
  routers:

    #################
    ### Sistemita ###
    #################
    web-secure-router:
      rule: "Host(`sistemita.liqueed.org`, `www.sistemita.liqueed.org`)"
      entryPoints:
        - web-secure
      middlewares:
        - csrf
        - sistemita-hosts
      service: django
      tls:
        # https://docs.traefik.io/master/routing/routers/#certresolver
        certResolver: letsencrypt

    nginx-secure-router:
      rule: "Host(`sistemita.liqueed.org`) || Host(`www.sistemita.liqueed.org`) && PathPrefix(`/media`)"
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: nginx
      tls:
        # https://docs.traefik.io/master/routing/routers/#certresolver
        certResolver: letsencrypt

    #############
    ### Fluid ###
    #############
    web-secure-router-fluid:
      rule: "Host(`sistemita-fluid.liqueed.org`, `www.sistemita-fluid.liqueed.org`)"
      entryPoints:
        - web-secure
      middlewares:
        - csrf
        - fluid-hosts
      service: django_fluid
      tls:
        # https://docs.traefik.io/master/routing/routers/#certresolver
        certResolver: letsencrypt

    nginx-fluid-secure-router:
      rule: "Host(`sistemita-fluid.liqueed.org`) || Host(`www.sistemita-fluid.liqueed.org`) && PathPrefix(`/media`)"
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: nginx_fluid
      tls:
        # https://docs.traefik.io/master/routing/routers/#certresolver
        certResolver: letsencrypt

  middlewares:
    csrf:
      # https://docs.traefik.io/master/middlewares/headers/#hostsproxyheaders
      # https://docs.djangoproject.com/en/dev/ref/csrf/#ajax
      headers:
        hostsProxyHeaders: ["X-CSRFToken"]

    sistemita-hosts:
      headers:
        allowedHosts:
          - "sistemita.liqueed.org"
          - "www.sistemita.liqueed.org"

    fluid-hosts:
      headers:
        allowedHosts:
          - "sistemita-fluid.liqueed.org"
          - "www.sistemita-fluid.liqueed.org"

  services:

    #################
    ### Sistemita ###
    #################
    django:
      loadBalancer:
        servers:
          - url: http://django:5000

    nginx:
      loadBalancer:
        servers:
          - url: http://sistemita.liqueed.org:8080/media/

    #############
    ### Fluid ###
    #############
    django_fluid:
      loadBalancer:
        servers:
          - url: http://django:5001

    nginx_fluid:
      loadBalancer:
        servers:
          - url: http://sistemita-fluid.liqueed.org:8081/media/

providers:
  # https://docs.traefik.io/master/providers/file/
  file:
    filename: /etc/traefik/traefik.yml
    watch: true
