# Generated by Django 3.0.7 on 2020-11-30 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0012_auto_20201119_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobranza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cliente')),
            ],
            options={
                'verbose_name': 'cobranza',
                'verbose_name_plural': 'cobranzas',
                'db_table': 'accounting_cliente_cobranza',
                'ordering': ('creado',),
            },
        ),
        migrations.CreateModel(
            name='CobranzaFactura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('ganancias', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('ingresos_brutos', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cobranza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobranza_facturas', to='accounting.Cobranza')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Factura')),
            ],
            options={
                'verbose_name': 'factura cobranza',
                'verbose_name_plural': 'facturas cobranza',
                'db_table': 'accounting_cliente_cobranza_factura',
            },
        ),
        migrations.CreateModel(
            name='CobranzaFacturaPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cobranza_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobranza_factura_pagos', to='accounting.CobranzaFactura')),
                ('metodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MedioPago')),
            ],
            options={
                'verbose_name': 'pago factura cobranza',
                'verbose_name_plural': 'pagos factura cobranza',
                'db_table': 'accounting_cliente_cobranza_factura_pago',
            },
        ),
    ]
