# Generated by Django 3.0.7 on 2020-12-13 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20201119_1411'),
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Proveedor')),
            ],
            options={
                'verbose_name': 'pago',
                'verbose_name_plural': 'pagos',
                'db_table': 'accounting_proveedor_pago',
                'ordering': ('creado',),
            },
        ),
        migrations.CreateModel(
            name='PagoFactura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('ganancias', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('ingresos_brutos', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.FacturaProveedor')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pago_facturas', to='accounting.Pago')),
            ],
            options={
                'verbose_name': 'factura pago',
                'verbose_name_plural': 'facturas pago',
                'db_table': 'accounting_proveedor_pago_factura',
            },
        ),
        migrations.CreateModel(
            name='PagoFacturaPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('metodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MedioPago')),
                ('pago_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pago_factura_pagos', to='accounting.PagoFactura')),
            ],
            options={
                'verbose_name': 'pago factura pago',
                'verbose_name_plural': 'pagos factura pago',
                'db_table': 'accounting_proveedor_pago_factura_pago',
            },
        ),
    ]
