# Generated by Django 3.0.7 on 2021-03-14 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_auto_20210107_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
